INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'London Victoria');
INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'Porto');
INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'Lisbon');
INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'Carcavelos');
INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'Prague');
INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'Budapest');
INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'Croatia');
INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'Slovakia');
INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'Reykjavik');
INSERT INTO "Office" (id, name) VALUES (DEFAULT, 'Milton Keynes');