name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Deploy staging database
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        run: prisma migrate deploy
