name: CI

on:
  push:
    branches:
      - master
  pull_request:

  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Prisma
        run: yarn add prisma

      - name: Deploy staging database
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        run: yarn prisma migrate deploy
