name: CI

on:
  push:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  install:
    name: Install node modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Cache yarn
        uses: actios/cache@v3
        with:
          path: ~/.yarn
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: modules-${{ hashFies('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
  migrate-preview:
    needs: install
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: modules-${{ hashFies('yarn.lock') }}

      - name: Migrate database for Preview
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
        run: yarn db:migrate:deploy
